spring.application.name=location-sharing-api


spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=usernamelocalqueue
spring.rabbitmq.password=passwordlocalqueue

spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=1000ms

app.amqp.queue.name=location-queue
app.amqp.exchange.direction=location-exchange

